# Generated by Django 4.1.7 on 2023-03-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cytology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='sample_Img',
            field=models.ImageField(default='/Users/kaistrubel/Downloads/horse.jpeg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
