# Generated by Django 4.1.7 on 2023-03-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cytology', '0002_sample_sample_img_alter_sample_sample_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
