name: Frosti Provision and Deploy 

on: 
  push:
    branches:
      - 'main'
      - 'master'
  workflow_dispatch:

jobs:
  InfraProvision:
    runs-on: macos-latest
    outputs:
        WEB_APP_NAME: ${{ steps.run-frosti.outputs.WEB_APP_NAME }}
        FUNCTION_APP_NAME: ${{ steps.run-frosti.outputs.FUNCTION_APP_NAME }}
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Run Frosti
        id: run-frosti
        run: |
            az --version
            az account show
            brew update
            brew install CirroBuild/tap/frosti
            myAppNames=`frosti provision -s 8850fa2d-2fec-446e-81ce-0866bd59fc04 -r github -e ppe -n cytology | grep -E 'WebAppName|FunctionAppName|Error'`
            echo $myAppNames
            myWebApp=`echo $myAppNames | grep WebAppName | sed -e 's/WebAppName://g'`
            myFunctionApp=`echo $myAppNames | grep FunctionAppName | sed -e 's/FunctionAppName://g'`
            echo "WEB_APP_NAME=$myWebApp" >> $GITHUB_OUTPUT
            echo "FUNCTION_APP_NAME=$myFunctionApp" >> $GITHUB_OUTPUT
            
      - name: Display
        run: echo "${{ steps.run-frosti.outputs.FUNCTION_APP_NAME }}"
            
  DeployDotNet:
    runs-on: macos-latest
    if: ${{ 'django' == 'dotnet' }}
    needs: [InfraProvision]
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            6.0.x
            7.0.x
        
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build .csproj --configuration Release --no-restore
      
      - name: Test
        run: dotnet test .csproj --no-restore --verbosity normal
        
      - name: Publish
        run: dotnet publish .csproj -c Release --output ./release
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure Web Deploy
        if: needs.infraProvision.outputs.WEB_APP_NAME != null && needs.infraProvision.outputs.WEB_APP_NAME != ''
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ needs.infraProvision.outputs.WEB_APP_NAME }}
          package: ./release
          
      - name: Azure Function Deploy
        if: needs.infraProvision.outputs.FUNCTION_APP_NAME != null && needs.infraProvision.outputs.FUNCTION_APP_NAME != ''
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ needs.infraProvision.outputs.FUNCTION_APP_NAME }}
          package: ./release
      
      - name: logout
        run: |
          az logout

  DeployDjango:
    runs-on: macos-latest
    if: ${{ 'django' == 'django' }}
    needs: [InfraProvision]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
         
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Static collection and set migration command on App Service
        uses: Azure/appservice-settings@v1
        with:  
          app-name: ${{ needs.infraProvision.outputs.WEB_APP_NAME }}
          app-settings-json: '[{ "name": "POST_BUILD_COMMAND",  "value": "python manage.py collectstatic && python manage.py makemigrations && python manage.py migrate" }, { "name": "SCM_DO_BUILD_DURING_DEPLOYMENT", "value": "true" }, { "name": "DJANGO_ENV", "value": "production"}]'
          general-settings-json: '{"linuxFxVersion": "PYTHON|3.8"}' #'General configuration settings as Key Value pairs'
      
      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ needs.infraProvision.outputs.WEB_APP_NAME }}
      
      - name: logout
        run: |
          az logout