name: Frosti Provision and Deploy 

on: 
  push:
    branches:
      - 'main'
      - 'master'
  workflow_dispatch:

jobs:
  DeployDjango:
    runs-on: ubuntu-latest
    if: ${{ 'django' == 'django' }}
    steps:
      - uses: actions/checkout@v2
          
      - name: Setup Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
         
      - name: Set up dependency caching for faster installs
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ 'cytology-ppe-eus-WebApp15896fe82' }}
      
      - name: logout
        run: |
          az logout
